services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: ["start","--features=declarative-ui", "--spi-user-provider=jpa-encrypted"]
    volumes: # Add keycloak plugins.
      - ./update-password-event-listener/target/update-password-event-listener-1.0.jar:/opt/keycloak/providers/update-password-event-listener.jar
      - ./pii-data-encryption-provider/target/pii-data-encryption-1.0.jar:/opt/keycloak/providers/pii-data-encryption.jar
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: "http://localhost:8080"
      KC_HTTP_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data_dev: